---
title: "Papers"
---


|    | Journal papers                                                                                                                                                                                                                                                                            |
|---:|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|  8 | Dardeno, Worden, Dervilis, Mills, **Bull** [On the hierarchical Bayesian modelling of frequency response functions](https://www.sciencedirect.com/science/article/pii/S0888327023009809) (2024)                                                                                           |
| 10 | Bee, Poole, Worden, Dervilis, **Bull** [Multitask feature selection within structural datasets](https://www.cambridge.org/core/journals/data-centric-engineering/article/multitask-feature-selection-within-structural-datasets/FC9171AF330232B4B07955F807C5BBD4) (2024)                  |
| 20 | Poole, Gardner, Dervilis, **Bull**, Worden [On statistic alignment for domain adaptation in structural health monitoring](https://journals.sagepub.com/doi/abs/10.1177/14759217221110441) (2023)                                                                                          |
| 21 | Gardner, **Bull**, Dervilis, Worden [Domain-adapted Gaussian mixture models for population-based structural health monitoring](https://link.springer.com/article/10.1007/s13349-022-00565-5) (2022)                                                                                       |
| 22 | Hughes, **Bull**, Gardner, Dervilis, Worden [On robust risk-based active-learning algorithms for enhanced decision support](https://www.sciencedirect.com/science/article/pii/S0888327022006124) (2022)                                                                                   |
| 23 | Dardeno, **Bull**, Mills, Dervilis, Worden [Modelling variability in vibration-based PBSHM via a generalised population form](https://www.sciencedirect.com/science/article/pii/S0022460X22004151) (2022)                                                                                 |
| 24 | **Bull**, Dhada, Steinert, Lindgren, Parlikad, Duncan, Girolami [Knowledge Transfer in Engineering Fleets: Hierarchical Bayesian Modelling for Multi-Task Learning](https://scholar.google.com/scholar?cluster=9172883967640918731&hl=en&oi=scholarr) (2022)                              |
| 25 | **Bull**, Dervilis, Worden, Cross, Rogers [A sampling-based approach for information-theoretic inspection management](https://royalsocietypublishing.org/doi/abs/10.1098/rspa.2021.0790) (2022)                                                                                           |
| 31 | Gardner, **Bull**, Gosliga, Poole, Dervilis, Worden [A population-based SHM methodology for heterogeneous structures: Transferring damage localisation knowledge between different aircraft wings](https://www.sciencedirect.com/science/article/pii/S0888327022001030) (2022)            |
| 32 | **Bull**, Gardner, Rogers, Dervilis, Cross, Papatheou, Maguire, Campos, Worden [Bayesian modelling of multivalued power curves from an operational wind farm](https://www.sciencedirect.com/science/article/pii/S0888327021008724) (2022)                                                 |
| 34 | Gardner, **Bull**, Dervilis, Worden [On the application of kernelised Bayesian transfer learning to population-based structural health monitoring](https://www.sciencedirect.com/science/article/pii/S088832702100861X) (2022)                                                            |
| 35 | Hughes, **Bull**, Gardner, Barthorpe, Dervilis, Worden [On risk-based active learning for structural health monitoring](https://www.sciencedirect.com/science/article/pii/S0888327021009055) (2022)                                                                                       |
| 42 | Gardner, **Bull**, Dervilis, Worden [Overcoming the problem of repair in structural health monitoring: Metric-informed transfer learning](https://www.sciencedirect.com/science/article/pii/S0022460X21003175) (2021)                                                                     |
| 44 | **Bull**, Gardner, Dervilis, Papatheou, Haywood-alexander, Mills, Worden [On the transfer of damage detectors between structures: An experimental case study](https://www.sciencedirect.com/science/article/pii/S0022460X21001449) (2021)                                                 |
| 45 | **Bull**, Gardner, Rogers, Cross, Dervilis, Worden [Probabilistic inference for structural health monitoring: new modes of learning from data](https://ascelibrary.org/doi/abs/10.1061/AJRUA6.0001106) (2021)                                                                             |
| 46 | Gardner, **Bull**, Gosliga, Dervilis, Worden [Foundations of population-based SHM, Part III: Heterogeneous populations–Mapping and transfer](https://www.sciencedirect.com/science/article/pii/S0888327020305288) (2021)                                                                  |
| 47 | **Bull**, Gardner, Gosliga, Rogers, Dervilis, Cross, Papatheou, Maguire, Campos, Worden [Foundations of population-based SHM, Part I: Homogeneous populations and forms](https://www.sciencedirect.com/science/article/pii/S0888327020305276) (2021)                                      |
| 48 | Gosliga, Gardner, **Bull**, Dervilis, Worden [Foundations of Population-based SHM, Part II: Heterogeneous populations–Graphs, networks, and communities](https://www.sciencedirect.com/science/article/pii/S0888327020305306) (2021)                                                      |
| 49 | Gardner, **Bull**, Gosliga, Poole, Dervilis, Worden [On a Population-Based Structural Health Monitoring Framework: An Aerospace Case Study](https://www.dpi-proceedings.com/index.php/shm2021/article/view/36243) (2021)                                                                  |
| 50 | Dardeno, Haywood-alexander, Mills, **Bull**, Dervilis, Worden [Investigating the effects of ambient temperature on feature consistency in vibration-based SHM](https://dpi-proceedings.com.destechpub.a2hosted.com/index.php/shm2021/article/view/36344) (2021)                           |
| 51 | Dardeno, **Bull**, Dervilis, Worden [Investigating experimental repeatability and feature consistency in vibration-based SHM](https://www.dpi-proceedings.com/index.php/shm2021/article/view/36346) (2021)                                                                                |
| 52 | Poole, Gardner, Dervilis, **Bull**, Worden [On normalisation for domain adaptation in population-based structural health monitoring](https://www.dpi-proceedings.com/index.php/shm2021/article/view/36280) (2021)                                                                         |
| 57 | Zammit, **Bull**, Sanders, Galvin, Dervilis, Sidhu, Worden [Towards the Probabilistic Analysis of Small Bowel Capsule Endoscopy Features to Predict Severity of Duodenal Histology in Patients with Villous Atrophy](https://link.springer.com/article/10.1007/s10916-020-01657-9) (2020) |
| 58 | Worden, **Bull**, Gardner, Gosliga, Rogers, Cross, Papatheou, Lin, Dervilis [A brief introduction to recent developments in population-based structural health monitoring](https://www.frontiersin.org/articles/10.3389/fbuil.2020.00146/full) (2020)                                     |
| 60 | **Bull**, Worden, Dervilis [Towards semi-supervised and probabilistic classification in structural health monitoring](https://www.sciencedirect.com/science/article/pii/S088832702030039X) (2020)                                                                                         |
| 66 | **Bull**, Rogers, Wickramarachchi, Cross, Worden, Dervilis [Probabilistic active learning: an online framework for structural health monitoring](https://www.sciencedirect.com/science/article/pii/S0888327019305096) (2019)                                                              |
| 67 | **Bull**, Worden, Fuentes, Manson, Cross, Dervilis [Outlier ensembles: A robust method for damage detection and unsupervised feature extraction from high-dimensional data](https://www.sciencedirect.com/science/article/pii/S0022460X1930197X) (2019)                                   |
| 75 | **Bull**, Worden, Manson, Dervilis [Active learning for semi-supervised structural health monitoring](https://www.sciencedirect.com/science/article/pii/S0022460X18305479) (2018)                                                                                                         |
 
|    | Preprints                                                                                                                                                                                                        |
|---:|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|  1 | Dardeno, **Bull**, Dervilis, Worden [When does a bridge become an aeroplane?](https://arxiv.org/abs/2411.18406) (2024)                                                                                           |
|  2 | Clarkson, **Bull**, Wickramarachchi, Cross, Rogers, Worden, Dervilis, Hughes [Active learning for regression in engineering populations: A risk-informed approach](https://arxiv.org/abs/2409.04328) (2024)      |
|  3 | Brealy, Hughes, Dardeno, **Bull**, Mills, Dervilis, Worden [Multitask learning for improved scour detection: A dynamic wave tank study](https://arxiv.org/abs/2408.16527) (2024)                                 |
|  6 | **Bull**, Jeon, Girolami, Duncan, Schooling, Haro [Towards Multilevel Modelling of Train Passing Events on the Staffordshire Bridge](https://arxiv.org/abs/2403.17820) (2024)                                    |
|  7 | Smith, Hughes, Dardeno, **Bull**, Dervilis, Worden [Anomaly Detection in Offshore Wind Turbine Structures using Hierarchical Bayesian Modelling](https://arxiv.org/abs/2402.19295) (2024)                        |
| 12 | Clarkson, **Bull**, Dardeno, Wickramarachchi, Cross, Rogers, Worden, Dervilis, Hughes [Sharing Information Between Machine Tools to Improve Surface Finish Forecasting](https://arxiv.org/abs/2310.05807) (2023) |
| 18 | Bee, **Bull**, Dervilis, Worden [When is an SHM problem a Multi-Task-Learning problem?](https://arxiv.org/abs/2305.09425) (2023)                                                                                 |
| 19 | **Bull**, Jones, Cross, Duncan, Girolami [Encoding domain expertise into multilevel models for source location](https://arxiv.org/abs/2305.08657) (2023)                                                         |
| 26 | Hughes, **Bull**, Gardner, Dervilis, Worden [Mitigating sampling bias in risk-based active learning via an EM algorithm](https://arxiv.org/abs/2206.12598) (2022)                                                |
| 27 | Dardeno, **Bull**, Dervilis, Worden [A generalised form for a homogeneous population of structures using an overlapping mixture of Gaussian processes](https://arxiv.org/abs/2206.11683) (2022)                  |
| 28 | Hughes, Gardner, **Bull**, Dervilis, Worden [Improving decision-making via risk-based active learning: Probabilistic discriminative classifiers](https://arxiv.org/abs/2206.11616) (2022)                        |
 
|    | Book chapters                                                                                                                                                                                                                                                                                                                                       |
|---:|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 11 | **Bull**, Abdallah, Mylonas, Avendaño-valencia, Tatsis, Gardner, Rogers, Brennan, Cross, Worden, Duncan, Dervilis, Girolami, Chatzi [Data-Centric Monitoring of Wind Farms](https://books.google.com/books?hl=en&lr=&id=x57WEAAAQBAJ&oi=fnd&pg=PA206&dq=info:opW30yPHEQIJ:scholar.google.com&ots=4hJqDfiRLw&sig=zoF7f3rVwlT5m2QngGMDM4H49Yw) (2023) |
| 37 | **Bull**, Hughes, Rogers, Gardner, Worden, Dervilis [Partially Supervised Learning for Data-Driven Structural Health Monitoring](https://link.springer.com/chapter/10.1007/978-3-030-81716-9_19) (2022)                                                                                                                                             |
| 38 | Gardner, **Bull**, Gosliga, Dervilis, Cross, Papatheou, Worden [Population-Based Structural Health Monitoring](https://link.springer.com/chapter/10.1007/978-3-030-81716-9_20) (2022)                                                                                                                                                               |
| 61 | Fuentes, Cross, Gardner, **Bull**, Rogers, Barthorpe, Shi, Dervilis, Farrar, Worden [Structural Health Monitoring and Damage Identification](https://link.springer.com/content/pdf/10.1007/978-1-4939-6503-8_23-1.pdf) (2020)                                                                                                                       |
 
|    | Thesis                                                                                                                                |
|---:|:--------------------------------------------------------------------------------------------------------------------------------------|
| 71 | **Bull** [Towards probabilistic and partially-supervised structural health monitoring](https://etheses.whiterose.ac.uk/26282/) (2019) |
 
|    | Conference papers                                                                                                                                                                                                                                                                                                                                                                               |
|---:|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|  4 | Brealy, **Bull**, Brennan, Beltrando, Sommer, Dervilis, Worden [On Additive Gaussian Processes for Wind Farm Power Prediction](https://link.springer.com/chapter/10.1007/978-3-031-61425-5_58) (2024)                                                                                                                                                                                           |
|  5 | Dardeno, **Bull**, Dervilis, Worden [Transfer learning via intermediate structures](https://eprints.whiterose.ac.uk/212847/) (2024)                                                                                                                                                                                                                                                             |
|  9 | Dardeno, **Bull**, Dervilis, Worden [Decoupling nonlinear normal modes using normalising flows](https://eprints.whiterose.ac.uk/212848/) (2024)                                                                                                                                                                                                                                                 |
| 13 | Dardeno, **Bull**, Mills, Dervilis, Worden [Hierarchical Bayesian modelling of a family of FRFs](https://eprints.whiterose.ac.uk/212849/) (2023)                                                                                                                                                                                                                                                |
| 14 | Dardeno, **Bull**, Mills, Dervilis, Worden [Hierarchical Bayes for population-based modelling of FRFs with temperature variation](https://eprints.whiterose.ac.uk/212850/) (2023)                                                                                                                                                                                                               |
| 15 | Dardeno, **Bull**, Dervilis, Worden [A population form via hierarchical Bayesian modelling of the FRF](https://link.springer.com/chapter/10.1007/978-3-031-34946-1_11) (2023)                                                                                                                                                                                                                   |
| 16 | Haywood-alexander, Worden, Dervilis, Mills, **Bull**, Dardeno [The Astir Glider Wing Dataset for Population-Based SHM](https://link.springer.com/chapter/10.1007/978-3-031-37007-6_3) (2023)                                                                                                                                                                                                    |
| 17 | Bee, Papatheou, Haywood-alexander, Mills, **Bull**, Worden, Dervilis [Better Together: Using Multi-Task Learning to Improve Feature Selection Within Structural Datasets](https://link.springer.com/chapter/10.1007/978-3-031-34946-1_7) (2023)                                                                                                                                                 |
| 29 | Poole, Gardner, Dervilis, **Bull**, Worden [On the application of partial domain adaptation for pbshm](https://link.springer.com/chapter/10.1007/978-3-031-07322-9_42) (2022)                                                                                                                                                                                                                   |
| 30 | Dhada, **Bull**, Girolami, Parlikad [Modelling the Times-to-Failures Using a Statistical Hierarchical Model](https://link.springer.com/chapter/10.1007/978-3-031-07258-1_99) (2022)                                                                                                                                                                                                             |
| 33 | **Bull**, Dhada, Steinert, Lindgren, Parlikad, Girolami [Population-Level Modelling for Truck Fleet Survival Analysis](https://www.repository.cam.ac.uk/items/f7d7fc3d-a2bd-412d-b7da-e5c5e40c1392) (2022)                                                                                                                                                                                      |
| 36 | Hughes, **Bull**, Gardner, Dervilis, Worden, Hughes [Semi-supervised risk-based active learning using inspection and maintenance information](https://eprints.whiterose.ac.uk/191598/) (2022)                                                                                                                                                                                                   |
| 39 | Gardner, **Bull**, Dervilis, Worden [Challenges for SHM from Structural Repairs: An Outlier-Informed Domain Adaptation Approach](https://link.springer.com/chapter/10.1007/978-3-030-76004-5_10) (2022)                                                                                                                                                                                         |
| 40 | Gardner, **Bull**, Dervilis, Worden [On the Application of Heterogeneous Transfer Learning to Population-Based Structural Health Monitoring](https://link.springer.com/chapter/10.1007/978-3-030-76004-5_11) (2022)                                                                                                                                                                             |
| 41 | **Bull**, Gardner, Dervilis, Papatheou, Haywood-alexander, Mills, Worden [Transferring Damage Detectors Between Tailplane Experiments](https://link.springer.com/chapter/10.1007/978-3-030-76004-5_22) (2022)                                                                                                                                                                                   |
| 43 | Hughes, **Bull**, Gardner, Barthorpe, Dervilis, Worden [A risk-based active learning approach to inspection scheduling](https://www.researchgate.net/profile/Aidan-Hughes-4/publication/355903488_A_risk-based_active_learning_approach_to_inspection_scheduling/links/61892373d7d1af224bc69a96/A-risk-based-active-learning-approach-to-inspection-scheduling.pdf) (2021)                      |
| 53 | **Bull**, Gardner, Dervilis, Papatheou, Worden [Automated Feature Extraction for Damage Detection: A Pseudo-fault Framework for Population-based SHM]() (2021)                                                                                                                                                                                                                                  |
| 54 | **Bull**, Gardner, Dervilis, Worden [Normalising Flows and Nonlinear Normal Modes](https://www.sciencedirect.com/science/article/pii/S240589632101209X) (2021)                                                                                                                                                                                                                                  |
| 55 | Gosliga, Gardner, **Bull**, Dervilis, Worden [Towards population-based structural health monitoring, Part III: Graphs, networks and communities](https://link.springer.com/chapter/10.1007/978-3-030-47717-2_26) (2021)                                                                                                                                                                         |
| 56 | Gosliga, Gardner, **Bull**, Dervilis, Worden [Towards population-based structural health monitoring, Part II: heterogeneous populations and structures as graphs](https://link.springer.com/chapter/10.1007/978-3-030-47717-2_17) (2021)                                                                                                                                                        |
| 59 | **Bull**, Gardner, Rogers, Cross, Dervilis, Worden [New Modes of Inference for Probabilistic SHM](https://link.springer.com/chapter/10.1007/978-3-030-64908-1_39) (2020)                                                                                                                                                                                                                        |
| 62 | Gardner, **Bull**, Gosliga, Dervilis, Worden [Towards population-based structural health monitoring, Part IV: heterogeneous populations, transfer and mapping](https://link.springer.com/chapter/10.1007/978-3-030-47638-0_20) (2020)                                                                                                                                                           |
| 63 | Gardner, **Bull**, Dervilis, Worden [Kernelised Bayesian transfer learning for population-based structural health monitoring](https://link.springer.com/chapter/10.1007/978-3-030-47638-0_22) (2020)                                                                                                                                                                                            |
| 64 | **Bull**, Gardner, Gosliga, Dervilis, Papatheou, Maguire, Campos, Rogers, Cross, Worden [Towards population-based structural health monitoring, Part I: Homogeneous populations and forms](https://link.springer.com/chapter/10.1007/978-3-030-47638-0_32) (2020)                                                                                                                               |
| 65 | **Bull**, Worden, Rogers, Cross, Dervilis [Investigating engineering data by probabilistic measures](https://link.springer.com/chapter/10.1007/978-3-030-12243-0_12) (2020)                                                                                                                                                                                                                     |
| 68 | **Bull**, Worden, Rogers, Wickramarachchi, Cross, Mcleay, Leahy, Dervilis [A probabilistic framework for online structural health monitoring: active learning from machining data streams](https://iopscience.iop.org/article/10.1088/1742-6596/1264/1/012028/meta) (2019)                                                                                                                      |
| 69 | **Bull**, Rogers, Dervilis, Cross, Worden [A Gaussian process form for population-based structural health monitoring](https://www.researchgate.net/profile/Lawrence-Bull-2/publication/334250549_A_Gaussian_process_form_for_population-based_structural_health_monitoring/links/622771023c53d31ba4b15c72/A-Gaussian-process-form-for-population-based-structural-health-monitoring.pdf) (2019) |
| 70 | **Bull**, Dervilis, Worden [Experimental Validation of the Population-Form to Represent Nominally-Identical Systems](https://www.dpi-proceedings.com/index.php/shm2019/article/view/32373) (2019)                                                                                                                                                                                               |
| 72 | **Bull**, Worden, Dervilis [Damage classification using labelled and unlabelled measurements](https://www.researchgate.net/profile/Lawrence-Bull-2/publication/337303717_Damage_Classification_Using_Labelled_and_Unlabelled_Measurements/links/62276fc93c53d31ba4b15c45/Damage-Classification-Using-Labelled-and-Unlabelled-Measurements.pdf) (2019)                                           |
| 73 | Dervilis, Zhang, **Bull**, Cross, Rogers, Fuentes, Dertimanis, Abdallah, Chatzi, Worden [A nonlinear robust outlier detection approach for SHM](https://eprints.whiterose.ac.uk/147321/) (2019)                                                                                                                                                                                                 |
| 74 | **Bull**, Manson, Worden, Dervilis [Active Learning Approaches to Structural Health Monitoring](https://link.springer.com/chapter/10.1007/978-3-319-75390-4_14) (2019)                                                                                                                                                                                                                          |
| 76 | **Bull**, Worden, Cross, Dervilis [Outlier Ensembles: an Alternative Robust Method for Inclusive Outlier Analysis with Structural Health Monitoring Data](https://scholar.google.com/scholar?cluster=10239515907274643620&hl=en&oi=scholarr) (2018)                                                                                                                                             |
| 77 | Clarkson, **Bull**, Dardeno, Wickramarachchi, Cross, Rogers, Worden, Dervilis, Hughes [A spin on active learning analysis for health monitoring](https://www.ndt.net/article/ewshm2024/papers/242_manuscript.pdf) (None)                                                                                                                                                                        |
 
| Other   |
|---------|